# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 06:18
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default='PZNLJVAA', max_length=255, unique=True)),
                ('description', models.TextField(default='', unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_PROCESS', 'On process'), ('CANCELLED', 'Cancelled'), ('DONE', 'Done')], default='AVAILABLE', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messenger_id', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENT', 'Agent')], default='CUSTOMER', max_length=255)),
                ('state', models.CharField(choices=[('INITIAL_STATE', 'Initial state'), ('CREATE_NEW_TASK', 'Create new task'), ('START_AGENT', 'Start agent'), ('TASK_IS_CREATED', 'Task is created'), ('UDPATED_TASK_AMOUNT', 'Updated task amount'), ('WAITING_FOR_AGENT', 'Waiting for agent'), ('TASK_SELECTED', 'Task selected'), ('TASK_ON_PROCESS', 'Task on process')], default='INITIAL_STATE', max_length=255)),
                ('recipient_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='chatbot.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='chatbot.User'),
        ),
    ]
