# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='reference_number',
            field=models.CharField(default='QJ4LBLBV', max_length=255, unique=True),
        ),
    ]
