# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20161126_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reference_number',
            field=models.CharField(default='EX3VRLJE4QLRVD', max_length=255),
        ),
    ]
