# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 09:41
from __future__ import unicode_literals

import chatbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20161126_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reference_number',
            field=models.CharField(default=chatbot.models.generate_reference_number, max_length=255, unique=True),
        ),
    ]
